import { readFile } from 'node:fs/promises'
import { describe, expect, it } from 'vitest'

describe('external thread runtime read-only wiring', () => {
  it('passes runtime ownership from App to the selected-thread composer and queue', async () => {
    const appSource = await readFile(new URL('../../App.vue', import.meta.url), 'utf8')
    const sidebarSource = await readFile(new URL('../sidebar/SidebarThreadTree.vue', import.meta.url), 'utf8')

    expect(appSource).toContain(':runtime-ownership="selectedThreadRuntimeOwnership"')
    expect(appSource).toContain(':externally-owned-thread-ids="externallyOwnedThreadIds"')
    expect(appSource).toContain(':disabled="selectedThreadRuntimeOwnership === \'external\'"')
    expect(appSource).toContain(':steer-disabled-message-ids="selectedThreadQueuedSteerDisabledMessageIds"')
    expect(appSource).toContain('const selectedThreadQueuedSteerDisabledMessageIds = computed(() => {')
    expect(appSource).toContain('return selectedThreadQueuedMessages.value.map((message) => message.id)')
    expect(appSource).toContain(':read-only="selectedThreadRuntimeOwnership === \'external\'"')
    expect(appSource).toMatch(/function onEditQueuedMessage\(messageId: string\): void \{\n  if \(selectedThreadRuntimeOwnership\.value === 'external'\) return/u)
    expect(sidebarSource).toContain('externallyOwnedThreadIds: string[]')
    expect(sidebarSource).toMatch(/function onForkThread\(threadId: string\): void \{\n  if \(isThreadExternallyOwned\(threadId\)\) return/u)
    expect(sidebarSource).toMatch(/function openRenameThreadDialog\(threadId: string, currentTitle: string\): void \{\n  if \(isThreadExternallyOwned\(threadId\)\) return/u)
    expect(sidebarSource).toMatch(/function openDeleteThreadDialog\(threadId: string, currentTitle: string\): void \{\n  if \(isThreadExternallyOwned\(threadId\)\) return/u)
  })

  it('hides conversation mutations and disables pending responses while externally owned', async () => {
    const conversationSource = await readFile(new URL('./ThreadConversation.vue', import.meta.url), 'utf8')
    const pendingRequestSource = await readFile(new URL('./ThreadPendingRequestPanel.vue', import.meta.url), 'utf8')

    expect(conversationSource).toContain('readOnly?: boolean')
    expect(conversationSource).not.toContain('showEditMessageButton')
    expect(conversationSource).toMatch(/const isSnapshotTextStreamingEnabled = computed\(\(\) =>\n  props\.readOnly === true/u)
    expect(conversationSource).toMatch(/function implementPlan\(message: UiMessage\): void \{\n  if \(props\.readOnly\) return/u)
    expect(pendingRequestSource).toContain('disabled?: boolean')
    expect(pendingRequestSource).toContain('<fieldset')
    expect(pendingRequestSource).toContain(':disabled="disabled"')
  })

  it('offers command approval with persistent execpolicy amendments', async () => {
    const pendingRequestSource = await readFile(new URL('./ThreadPendingRequestPanel.vue', import.meta.url), 'utf8')

    expect(pendingRequestSource).toContain('Approve for me')
    expect(pendingRequestSource).toContain('proposedExecpolicyAmendment')
    expect(pendingRequestSource).toContain('acceptWithExecpolicyAmendment')
    expect(pendingRequestSource).toContain('approved_execpolicy_amendment')
    expect(pendingRequestSource).not.toContain('Tool call waiting for response')
    expect(pendingRequestSource).toContain("isPermissionsApprovalRequest(request)")
    expect(pendingRequestSource).toContain('Approve for me')
  })

  it('keeps externally owned transcript mutations read-only while preserving the complete queued payload', async () => {
    const composerSource = await readFile(new URL('./ThreadComposer.vue', import.meta.url), 'utf8')

    expect(composerSource).toContain('runtimeOwnership?: ThreadRuntimeOwnership')
    expect(composerSource).toContain("const isExternallyOwned = computed(() => props.runtimeOwnership === 'external')")
    expect(composerSource).toMatch(/const isInteractionDisabled = computed\(\(\) => props\.disabled \|\| !props\.activeThreadId\)/u)
    expect(composerSource).toMatch(/const isAttachmentControlDisabled = computed\(\(\) => isExternallyOwned\.value \|\| isInteractionDisabled\.value\)/u)
    expect(composerSource).toContain(':disabled="isAttachmentControlDisabled"')
    expect(composerSource).toMatch(/class="thread-composer-attachment-remove"[\s\S]*?:disabled="isAttachmentControlDisabled"/u)
    expect(composerSource).toMatch(/class="thread-composer-folder-chip-remove"[\s\S]*?:disabled="isAttachmentControlDisabled"/u)
    expect(composerSource).toMatch(/class="thread-composer-file-chip-remove"[\s\S]*?:disabled="isAttachmentControlDisabled"/u)
    expect(composerSource).toMatch(/class="thread-composer-skill-chip-name"[\s\S]*?:disabled="isAttachmentControlDisabled"/u)
    expect(composerSource).toMatch(/class="thread-composer-skill-chip-remove"[\s\S]*?:disabled="isAttachmentControlDisabled"/u)
    expect(composerSource).not.toMatch(/if \(isExternallyOwned\.value\) return draft\.value\.trim\(\)\.length > 0/u)
    expect(composerSource).toContain('const imageUrls = selectedImages.value.map(toSelectedImageUrl)')
    expect(composerSource).toContain('const submitFileAttachments = [...fileAttachments.value]')
    expect(composerSource).toContain('const submitSkills = selectedSkills.value.map((s) => ({ name: s.name, path: s.path }))')
    expect(composerSource).toMatch(/function triggerPhotoLibrary\(\): void \{\n  if \(isAttachmentControlDisabled\.value\) return/u)
    expect(composerSource).toMatch(/function removeImage\(id: string\): void \{\n  if \(isAttachmentControlDisabled\.value\) return/u)
    expect(composerSource).toMatch(/function removeFileAttachment\(fsPath: string\): void \{\n  if \(isAttachmentControlDisabled\.value\) return/u)
    expect(composerSource).toMatch(/function removeFolderAttachment\(groupId: string\): void \{\n  if \(isAttachmentControlDisabled\.value\) return/u)
    expect(composerSource).toMatch(/function removeSkill\(path: string\): void \{\n  if \(isAttachmentControlDisabled\.value\) return/u)
    expect(composerSource).toMatch(/function openSkillMarkdown\(skill: SkillItem\): void \{\n  if \(isAttachmentControlDisabled\.value\) return/u)
    expect(composerSource).toMatch(/function onInputKeydown\(event: KeyboardEvent\): void \{\n  if \(isFileMentionOpen\.value && !isAttachmentControlDisabled\.value\) \{/u)
    expect(composerSource).toMatch(/function updateFileMentionState\(\): void \{\n  if \(isAttachmentControlDisabled\.value\) \{\n    closeFileMention\(\)\n    return\n  \}/u)
    expect(composerSource).toMatch(/async function queueFileMentionSearch\(\): Promise<void> \{\n  if \(!isFileMentionOpen\.value \|\| isAttachmentControlDisabled\.value\) return/u)
    expect(composerSource).toMatch(/fileMentionDebounceTimer = setTimeout\(async \(\) => \{\n    if \(isAttachmentControlDisabled\.value\) \{/u)
    expect(composerSource).toContain('fileAttachments.value = []')
    expect(composerSource).toContain('selectedSkills.value = []')
    expect(composerSource).not.toMatch(/if \(isExternallyOwned\.value\) invalidatePendingAttachments\(\)/u)
    expect(composerSource).not.toContain("primaryAction === 'externalRunning'")
    expect(composerSource).not.toMatch(/function onSubmit\(mode: 'steer' \| 'queue' = 'steer'\): void \{\n  if \(isExternallyOwned\.value\) return/u)
    expect(composerSource).not.toMatch(/function onInterrupt\(\): void \{\n  if \(isExternallyOwned\.value\) return/u)
    expect(composerSource).toMatch(/function hydrateDraft\(payload: ComposerDraftPayload\): void \{\n  if \(isExternallyOwned\.value\) return/u)
    expect(composerSource).toMatch(/function appendTextToDraft\(text: string\): void \{\n  if \(isExternallyOwned\.value\) return/u)
    expect(composerSource).toMatch(/onTranscript: \(text\) => \{\n    if \(!canApplyThreadUiMutation\(props\.runtimeOwnership\)\) return/u)
    expect(composerSource).toContain('applyExternalRuntimeTakeover(previousOwnership, ownership, {')
    expect(composerSource).toContain('canApplyAttachmentMutation(props.runtimeOwnership, sessionToken, attachmentSessionToken)')
  })

  it('offers max and ultra reasoning plus fast mode for GPT 5.6 families', async () => {
    const composerSource = await readFile(new URL('./ThreadComposer.vue', import.meta.url), 'utf8')

    expect(composerSource).toContain('getSupportedReasoningEfforts')
    expect(composerSource).toContain('desktopModelEffortOptions')
    expect(composerSource).toContain('composerControlState.value.selectedEffort')
    expect(composerSource).toContain("const isFastModeSupported = computed(() => /^gpt-5\\.(?:4|5|6)(?:$|-)/.test(props.selectedModel.trim()))")
  })

  it('keeps queued-message steer available while guarding edit, delete, and reorder controls', async () => {
    const queueSource = await readFile(new URL('./QueuedMessages.vue', import.meta.url), 'utf8')

    expect(queueSource).toContain(':disabled="disabled"')
    expect(queueSource).toContain(':disabled="isSteerDisabled(msg.id)"')
    expect(queueSource).toContain('steerDisabledMessageIds?: string[]')
    expect(queueSource).not.toContain("$emit('edit'")
    expect(queueSource).not.toContain("$emit('steer'")
    expect(queueSource).not.toContain("$emit('delete'")
    expect(queueSource).toMatch(/function onEdit\(messageId: string\): void \{\n  if \(props\.disabled\) return\n  emit\('edit', messageId\)/u)
    expect(queueSource).toMatch(/function onSteer\(messageId: string\): void \{\n  if \(isSteerDisabled\(messageId\)\) return\n  emit\('steer', messageId\)/u)
    expect(queueSource).toMatch(/function onDelete\(messageId: string\): void \{\n  if \(props\.disabled\) return\n  emit\('delete', messageId\)/u)
    expect(queueSource).toMatch(/function onMove\(messageId: string, direction: -1 \| 1\): void \{\n  if \(props\.disabled\) return/u)
    expect(queueSource).not.toContain('@dragstart=')
  })
})
