import { ref } from 'vue'

export type UiLanguage = 'en' | 'zh-CN'

const UI_LANGUAGE_STORAGE_KEY = 'codex-web-local.ui-language.v1'

const zhCN: Record<string, string> = {
  'English': 'English',
  'Simplified Chinese': '简体中文',
  'Search threads': '搜索线程',
  'Filter threads...': '筛选线程...',
  'Clear search': '清除搜索',
  'Chats': '聊天',
  'Projects': '项目',
  'Pinned': '已固定',
  'Chats first': '聊天优先',
  'Sort by': '排序',
  'Created': '创建时间',
  'Updated': '更新时间',
  'New chat': '新聊天',
  'No chats': '没有聊天',
  'Skills Hub': '技能中心',
  'Expand accounts': '展开账户',
  'Collapse accounts': '折叠账户',
  'Accounts': '账户',
  'Reloading…': '重新加载中…',
  'Reload': '重新加载',
  'Run `codex login`, then click reload.': '先运行 `codex login`，然后点击重新加载。',
  'Account': '账户',
  'Workspace': '工作区',
  'Require ⌘ + enter to send': '需要 ⌘ + Enter 才发送',
  'When busy, send as': '忙碌时发送方式',
  'Steer': '引导',
  'Queue': '排队',
  'Appearance': '外观',
  'System': '跟随系统',
  'Dark': '深色',
  'Light': '浅色',
  'Chat width': '聊天宽度',
  'Click to toggle dictation': '点击切换语音输入',
  'Auto send dictation': '语音输入后自动发送',
  'Provider': '提供方',
  'Choose the API provider for the Codex backend': '选择 Codex 后端使用的 API 提供方',
  'OpenRouter API key': 'OpenRouter API Key',
  'Get API key': '获取 API Key',
  'Remove custom key, use community keys': '移除自定义 key，改用社区 key',
  'Set': '设置',
  'Save': '保存',
  'API format': 'API 格式',
  'OpenRouter API format': 'OpenRouter API 格式',
  'Responses': 'Responses',
  'Completions': 'Completions',
  'OpenCode Zen API key': 'OpenCode Zen API Key',
  'Custom endpoint URL': '自定义端点 URL',
  'API key': 'API Key',
  'Custom endpoint API format': '自定义端点 API 格式',
  'UI language': '界面语言',
  'Choose the interface language for the app.': '选择应用界面语言。',
  'Dictation language': '听写语言',
  'Auto-detect': '自动检测',
  'Search language...': '搜索语言...',
  'Telegram': 'Telegram',
  'Bot token': 'Bot Token',
  'Allowed Telegram user IDs': '允许的 Telegram 用户 ID',
  'Put one Telegram user ID per line or separate them with commas. Use `*` to allow all Telegram users. Unauthorized users will see their own ID in the rejection message so they can copy it here.': '每行填写一个 Telegram 用户 ID，或用逗号分隔。使用 `*` 可允许所有 Telegram 用户。未授权用户会在拒绝消息中看到自己的 ID，方便复制到这里。',
  'Saving…': '保存中…',
  'Save Telegram config': '保存 Telegram 配置',
  'Context': '上下文',
  'Worktree name and version': '工作树名称和版本',
  'Settings': '设置',
  'Toggle terminal': '切换终端',
  'Open terminal': '打开终端',
  'Terminal command': '终端命令',
  'No commands': '没有命令',
  'Search branches...': '搜索分支...',
  "Let's build": '开始构建',
  'Choose folder': '选择文件夹',
  'Quick search project': '快速搜索项目',
  'Selected folder': '已选文件夹',
  'Select folder': '选择文件夹',
  'Create Project': '创建项目',
  'Create or clone': '创建或克隆',
  'Create or clone project': '创建或克隆项目',
  'Project source': '项目来源',
  'New project': '新项目',
  'Destination folder': '目标文件夹',
  'New project name': '新项目名称',
  'GitHub repository URL': 'GitHub 仓库 URL',
  'Create project': '创建项目',
  'Creating…': '创建中…',
  'Clone repository': '克隆仓库',
  'Clone from GitHub': '从 GitHub 克隆',
  'Cloning…': '克隆中…',
  'Current folder': '当前文件夹',
  'Unavailable': '不可用',
  'Opening…': '打开中…',
  'Open': '打开',
  'Show hidden folders': '显示隐藏文件夹',
  'New folder': '新建文件夹',
  'Folder name': '文件夹名称',
  'Filter folders...': '筛选文件夹...',
  'Retry': '重试',
  'Loading folders…': '加载文件夹中…',
  'No folders match this filter.': '没有匹配此筛选条件的文件夹。',
  'No subfolders found here.': '这里没有子文件夹。',
  'Base branch': '基础分支',
  'Select branch': '选择分支',
  'Loading branches…': '加载分支中…',
  'No Git branches found for this folder.': '此文件夹未找到 Git 分支。',
  'Local project': '本地项目',
  'New worktree': '新工作树',
  'Service worker registration failed.': 'Service Worker 注册失败。',
  'No matching files': '没有匹配的文件',
  'Add photos & files': '添加图片和文件',
  'Add folder': '添加文件夹',
  'Take photo': '拍照',
  'In-progress send': '执行中发送',
  'Fast mode': '快速模式',
  'Plan mode': '规划模式',
  'Agent proposes a plan before acting': '代理在执行前先提出计划',
  'Model': '模型',
  'Search models...': '搜索模型...',
  'Skills': '技能',
  'Search skills...': '搜索技能...',
  'Search skills and prompts...': '搜索技能和提示词...',
  'Thinking': '思考强度',
  'Saving thread before stop is available': '线程保存后才能停止',
  'Running in another client': '正在其他客户端中运行',
  'Stop': '停止',
  'Queue message': '加入队列',
  'Send message': '发送消息',
  'Send': '发送',
  'Drop images or files': '拖放图片或文件',
  'Selected image': '已选图片',
  'Loading messages...': '加载消息中...',
  'Plan': '计划',
  'Updating': '更新中',
  'Edit this message': '编辑此消息',
  'Edit message': '编辑消息',
  'Fork thread from this response': '从此回复分叉线程',
  'Fork': '分叉',
  'Response copied': '回复已复制',
  'Copy response': '复制回复',
  'Jump to latest': '跳转到最新',
  'Jump to latest output': '跳转到最新输出',
  'Close image preview': '关闭图片预览',
  'Expanded message image': '放大消息图片',
  'Changed files': '已更改文件',
  'Close diff viewer': '关闭 diff 查看器',
  'No diff available': '没有可用 diff',
  'This summary was restored from the final answer text, but the thread history does not include patch diff content for this file.': '此摘要是从最终回答文本恢复的，但线程历史中不包含该文件的补丁 diff 内容。',
  'Review': '审查',
  'Commit': '提交',
  'Close review pane': '关闭审查面板',
  'Compare': '比较',
  'Branch': '分支',
  'Changes': '更改',
  'Loading review state': '加载审查状态中',
  'This folder is not a Git repository': '此文件夹不是 Git 仓库',
  'Initialize Git to review local changes and run Codex review.': '初始化 Git 后即可审查本地更改并运行 Codex review。',
  'Initializing…': '初始化中…',
  'Initialize Git': '初始化 Git',
  'Base branch unavailable': '基础分支不可用',
  'Could not resolve `origin/HEAD`, `main`, or `master` for this repository.': '无法为此仓库解析 `origin/HEAD`、`main` 或 `master`。',
  'No changes in this scope': '此范围内没有更改',
  'No file changes in this commit.': '此提交中没有文件更改。',
  'Your current workspace is clean.': '当前工作区很干净。',
  'No merge diff found against the base branch.': '未找到相对基础分支的合并 diff。',
  'No unified diff available.': '没有可用的统一 diff。',
  'Summary': '摘要',
  'Added': '新增',
  'Deleted': '删除',
  'Renamed': '重命名',
  'Modified': '修改',
  'Repository review': '仓库审查',
  'Staged changes': '已暂存更改',
  'Workspace changes': '工作区更改',
  'Unstage all': '全部取消暂存',
  'Stage all': '全部暂存',
  'Revert all': '全部还原',
  'Unstage file': '取消暂存文件',
  'Stage file': '暂存文件',
  'Revert file': '还原文件',
  'Unstage hunk': '取消暂存代码块',
  'Stage hunk': '暂存代码块',
  'Revert hunk': '还原代码块',
  'Failed to load review snapshot': '加载审查快照失败',
  'Failed to apply review action': '应用审查操作失败',
  'Failed to initialize Git': '初始化 Git 失败',
  'Reviewing current changes': '正在审查当前更改',
  'Failed to start review': '启动审查失败',
  'Review in progress': '审查进行中',
  'Failed to load review result': '加载审查结果失败',
  'pin': '固定',
  'Worktree thread': '工作树线程',
  'Threads': '线程',
  'Organize threads': '整理线程',
  'Organize': '整理',
  'By project': '按项目',
  'Chronological list': '按时间顺序',
  'No matching threads': '没有匹配的线程',
  'Loading threads...': '加载线程中...',
  'Edit name': '编辑名称',
  'Remove': '移除',
  'Project name': '项目名称',
  'No threads': '没有线程',
  'Thread title': '线程标题',
  'Rename thread': '重命名线程',
  'Make it short and recognizable.': '尽量简短且易识别。',
  'Add title...': '输入标题...',
  'Cancel': '取消',
  'Delete thread': '删除线程',
  'Thread automation': '线程自动化',
  'This creates a heartbeat automation attached to the selected thread.': '这会创建一个附加到所选线程的心跳自动化。',
  'Name': '名称',
  'Automation name': '自动化名称',
  'Prompt': '提示词',
  'Search prompt...': '搜索提示词...',
  'Describe what the automation should do': '描述自动化需要执行的内容',
  'Schedule (RRULE)': '计划（RRULE）',
  'Status': '状态',
  'Active': '启用',
  'Paused': '暂停',
  'Expand sidebar': '展开侧边栏',
  'Collapse sidebar': '折叠侧边栏',
  'Start new thread': '新建线程',
  'No skills found': '未找到技能',
  'No results': '没有结果',
  'Approval choices': '审批选项',
  'No, and tell Codex what to do differently': '不允许，并告诉 Codex 应如何调整',
  'Skip': '跳过',
  'Server': '服务器',
  'Open authorization link': '打开授权链接',
  'Value': '值',
  'Choice': '选项',
  'Select true or false': '选择 true 或 false',
  'True': 'True',
  'False': 'False',
  'Select an option': '选择一个选项',
  'Decline': '拒绝',
  'Continue': '继续',
  'Other answer': '其他答案',
  'Fail Tool Call': '使工具调用失败',
  'Success (Empty)': '成功（空结果）',
  'Return Empty Result': '返回空结果',
  'New terminal': '新终端',
  'Hide terminal': '隐藏终端',
  'Close': '关闭',
  'Edit queued message': '编辑排队消息',
  'Send now without interrupting work': '立即发送且不中断当前工作',
  'Delete queued message': '删除排队消息',
  'AppServer API': 'AppServer API',
  'Loading method catalog...': '加载方法目录中...',
  'Disabled': '已禁用',
  'Installed': '已安装',
  'Browse files': '浏览文件',
  'Loading skill contents...': '加载技能内容中...',
  'View on GitHub': '在 GitHub 查看',
  'Show all': '显示全部',
  'Hide all': '隐藏全部',
  'No types yet': '还没有类型',
  'Manage installed skills on this machine': '管理此机器上已安装的技能',
  'Skills Sync (GitHub)': '技能同步（GitHub）',
  'Connected': '已连接',
  'Logged in as': '已登录为',
  'Not connected': '未连接',
  'Startup': '启动',
  'Action': '动作',
  'Manual sync': '手动同步',
  'GitHub device login': 'GitHub 设备登录',
  'and enter code:': '并输入代码：',
  'Login with GitHub': '使用 GitHub 登录',
  'Device Login': '设备登录',
  'Logout GitHub': '退出 GitHub',
  'Syncing...': '同步中...',
  'Startup Sync': '启动同步',
  'Pulling...': '拉取中...',
  'Pull': '拉取',
  'Pushing...': '推送中...',
  'Push': '推送',
  'Installed ({count})': '已安装（{count}）',
  'Find skills': '查找技能',
  'Search the Skills registry with npx skills find.': '使用 npx skills find 搜索 Skills 注册表。',
  'Searching...': '搜索中...',
  'Search results ({count})': '搜索结果（{count}）',
  'No matching skills found.': '未找到匹配的技能。',
  'No installed skills found.': '未找到已安装的技能。',
  'Continue in': '运行方式',
  'Search daily': '搜索（日）',
  'Search weekly': '搜索（周）',
  'Search monthly': '搜索（月）',
  'Trending daily': '热门（日）',
  'Trending weekly': '热门（周）',
  'Trending monthly': '热门（月）',
  'Newest': '最新',
  'A-Z': 'A-Z',
  'Loading skills...': '加载技能中...',
  'Choose a thread': '选择一个线程',
  'New worktree branch will start from {branch}.': '新工作树分支将从 {branch} 开始。',
  'Local project uses the selected folder directly. New worktree creates an isolated Git worktree before the first prompt.': '本地项目会直接使用所选文件夹。新工作树会在第一次提问前创建一个隔离的 Git worktree。',
  'Not configured': '未配置',
  'Online': '在线',
  'Configured (offline)': '已配置（离线）',
  'allow all users': '允许所有用户',
  'allowed user(s)': '个允许用户',
  'chat(s)': '个聊天',
  'thread(s)': '个线程',
  'error': '错误',
  'unknown': '未知',
  'Switching…': '切换中…',
  'Switch': '切换',
  'Removing…': '移除中…',
  'Click again to remove': '再次点击以移除',
  '402 Payment Required': '402 需要付费',
  'weekly remaining': '周剩余额度',
  'Unlimited credits': '无限额度',
  'credits': '额度',
  'Loading quota…': '加载额度中…',
  'Quota unavailable': '额度不可用',
  'Fetching account details…': '获取账户详情中…',
  'Unavailable account': '不可用账户',
  'Waiting for Codex thread/tokenUsage/updated events for this thread.': '等待此线程的 Codex tokenUsage 更新事件。',
  'Current context usage': '当前上下文使用量',
  'Cumulative thread usage': '累计线程使用量',
  'Model context window': '模型上下文窗口',
  'Remaining context': '剩余上下文',
  'tokens': 'tokens',
  'Model context window is unavailable in the latest usage event.': '最新使用事件中未提供模型上下文窗口。',
  'Awaiting data': '等待数据中',
  'left': '剩余',
  'used': '已用',
  'Updates after the next token usage event': '下次 token 使用事件后更新',
  'Window size unavailable': '窗口大小不可用',
  'Telegram bot token is required.': '需要填写 Telegram Bot Token。',
  'At least one allowed Telegram user ID or * is required.': '至少需要一个允许的 Telegram 用户 ID 或 `*`。',
  'Telegram bot configured. Only allowlisted Telegram users can use the bridge.': 'Telegram 机器人已配置。只有白名单中的 Telegram 用户可以使用桥接。',
  'Failed to connect Telegram bot': '连接 Telegram 机器人失败',
  'Failed to load accounts': '加载账户失败',
  'Failed to refresh accounts': '刷新账户失败',
  'Login': '登录',
  'Starting login…': '正在启动登录…',
  'Open login URL': '打开登录链接',
  'Paste localhost callback URL': '粘贴 localhost 回调 URL',
  'Complete Codex login': '完成 Codex 登录',
  'Finish login in the browser, then paste the localhost callback URL here.': '在浏览器中完成登录，然后在这里粘贴 localhost 回调 URL。',
  'Complete': '完成',
  'Completing…': '正在完成…',
  'Failed to start Codex login': '启动 Codex 登录失败',
  'Failed to complete Codex login': '完成 Codex 登录失败',
  'Click Login, or run `codex login`, then click reload.': '点击登录，或运行 `codex login`，然后点击重新加载。',
  'Finish the current turn and pending requests before switching accounts.': '请先完成当前轮次并处理待处理请求后再切换账户。',
  'Failed to switch account': '切换账户失败',
  'Finish the current turn and pending requests before removing the active account.': '请先完成当前轮次并处理待处理请求后再移除当前活动账户。',
  'Failed to remove account': '移除账户失败',
  'enabled': '已启用',
  'disabled': '已禁用',
  'Saving speed setting...': '保存速度设置中...',
  'About 1.5x faster, with credits used at 2x': '速度约提升 1.5 倍，额度消耗为 2 倍',
  'Default speed with normal credit usage': '默认速度，按正常额度消耗',
  'Stop dictation': '停止听写',
  'Click to dictate': '点击开始听写',
  'Hold to dictate': '按住听写',
  'failed': '失败',
  'attaching': '正在附加',
  'Attaching': '正在附加',
  'Attaching file...': '正在附加文件...',
  'files...': '个文件...',
  'attached': '已附加',
  'Could not attach file.': '无法附加文件。',
  'Could not attach': '无法附加',
  'files.': '个文件。',
  'Select a thread to send a message': '选择一个线程后才能发送消息',
  'Loading models for plan mode...': '正在为规划模式加载模型...',
  'Type a message... (@ for files)': '输入消息...（@ 选择文件）',
  'Hide': '隐藏',
  'Terminal': '终端',
  'Terminal input failed': '终端输入失败',
  'Terminal attach failed': '终端附加失败',
  'Creating worktree': '创建工作树',
  'Creating a worktree and running setup.': '正在创建工作树并执行初始化。',
  'Worktree setup failed': '工作树初始化失败',
  'Unable to create worktree. Try again or switch to Local project.': '无法创建工作树。请重试，或切换到本地项目。',
  'Edit': '编辑',
  'image': '图片',
  'images': '图片',
  'file': '文件',
  'files': '文件',
  'skill': '技能',
  'skills': '技能',
  '(empty queued message)': '（空的排队消息）',
  'Files': '文件',
  'Unstaged': '未暂存',
  'Staged': '已暂存',
  'Refresh': '刷新',
  'Against': '对比',
  'selected': '已选',
  'Reject Request': '拒绝请求',
  'Uninstalling...': '卸载中...',
  'Uninstall': '卸载',
  'Installing...': '安装中...',
  'Install': '安装',
  'Disable': '禁用',
  'Enable': '启用',
  'When enabled, press Enter to send. When disabled, use Command+Enter to send.': '启用时按 Enter 发送；禁用时使用 Command+Enter 发送。',
  'If a turn is still running, choose whether a new prompt should steer the current turn or be queued.': '如果当前轮次仍在运行，选择新提示是引导当前轮次还是加入队列。',
  'Switch between system theme, light mode, and dark mode.': '在跟随系统、浅色和深色主题之间切换。',
  'Choose how wide the conversation column and composer can grow on desktop screens.': '选择桌面端会话列和输入框的最大宽度。',
  'Use click-to-start and click-to-stop dictation instead of hold-to-talk.': '使用点击开始/停止听写，而不是按住说话。',
  'Automatically send transcribed dictation when recording stops.': '录音停止后自动发送转写结果。',
  'Show or hide GitHub trending project cards on the new thread screen.': '显示或隐藏新线程页面上的 GitHub 热门项目卡片。',
  'Choose transcription language or keep auto-detect.': '选择转写语言，或保持自动检测。',
  'Standard': '标准',
  'Wide': '宽',
  'Extra wide': '超宽',
}

const LANGUAGE_LABELS: Record<UiLanguage, string> = {
  en: 'English',
  'zh-CN': '简体中文',
}

function readStoredLanguage(): UiLanguage {
  if (typeof window === 'undefined') return 'en'
  const raw = window.localStorage.getItem(UI_LANGUAGE_STORAGE_KEY)?.trim()
  return raw === 'zh-CN' ? 'zh-CN' : 'en'
}

const currentLanguage = ref<UiLanguage>(readStoredLanguage())

function applyDocumentLanguage(language: UiLanguage): void {
  if (typeof document === 'undefined') return
  document.documentElement.lang = language === 'zh-CN' ? 'zh-CN' : 'en'
  document.documentElement.dataset.uiLanguage = language
}

applyDocumentLanguage(currentLanguage.value)

function formatTemplate(template: string, params?: Record<string, string | number>): string {
  if (!params) return template
  return template.replace(/\{(\w+)\}/g, (_match, key: string) => String(params[key] ?? ''))
}

export function setUiLanguage(language: UiLanguage): void {
  currentLanguage.value = language
  applyDocumentLanguage(language)
  if (typeof window !== 'undefined') {
    window.localStorage.setItem(UI_LANGUAGE_STORAGE_KEY, language)
  }
}

export function t(message: string, params?: Record<string, string | number>): string {
  const translated = currentLanguage.value === 'zh-CN' ? (zhCN[message] ?? message) : message
  return formatTemplate(translated, params)
}

export function useUiLanguage() {
  return {
    uiLanguage: currentLanguage,
    uiLanguageOptions: [
      { value: 'en', label: LANGUAGE_LABELS.en },
      { value: 'zh-CN', label: LANGUAGE_LABELS['zh-CN'] },
    ] as Array<{ value: UiLanguage; label: string }>,
    t,
    setUiLanguage,
  }
}
